/* eslint-disable quote-props */ /* eslint-disable max-len */
export const SECTORS = {
  'Waste management, including street cleaning and winter road maintenance': 'Abfallwirtschaft, einschließlich Straßenreinigung und Winterdienst',
  'Setting up and dismantling trade fairs and exhibitions': 'Auf- und Abbau von Messen und Ausstellungen',
  'Further educational services - training and further training services': 'Aus- und Weiterbildungsdienstleistungen nach dem Zweiten oder Dritten Buch Sozialgesetzbuch',
  'Construction industry': 'Bauhauptgewerbe und Baunebengewerbe',
  'Special mining activities in coal mines': 'Bergbauspezialarbeiten auf Steinkohlebergwerken (BSA)',
  'Mail services sector': 'Briefdienstleistungen',
  'Slaughter and meat processing (processing and preserving of meat and production of meat products)': 'Fleischwirtschaft einschl. Schlachten und Fleischverarbeitung',
  'Catering and hotel business': 'Gaststätten- und Beherbergungsgewerbe',
  'Industrial cleaning services': 'Gebäudereinigung',
  'Scaffolding erection': 'Gerüstbauerhandwerk',
  'No information': 'Sonstige',
  'Agriculture, forestry, and horticulture': 'Land- und Forstwirtschaft sowie Gartenbau',
  'Passenger transportation industry': 'Personenbeförderungsgewerbe',
  'Care provision sector': 'Pflegedienstleistungen',
  'Prostitution industry': 'Prostitutionsgewerbe',
  'Fairground and amusement sector': 'Schaustellergewerbe',
  'Chimney sweep': 'Schornsteinfegerhandwerk',
  'Others': 'Sonstige',
  'Haulage, transport (including cabotage operations, cross-border transports with loading and unloading in Germany), and associated logistics industry': 'Speditions-, Transport- und damit verbundenes Logistikgewerbe',
  'Textile and clothing industry': 'Textil- und Bekleidungsindustrie',
  'Security services (excl. money and valuable services)': 'Wach- und Sicherheitsgewerbe',
  'Laundry services in the commercial customer business': 'Wäschereidienstleistungen im Objektkundengeschäft',
  'Electrician\'s trade': 'Sonstige',
  'Gardening, landscaping and sports fields': 'Sonstige',
  'Hairdressing sector': 'Sonstige',
  'Installation services on construction sites of the iron, metal and electrical industries': 'Sonstige',
  'Money and valuable services': 'Sonstige',
  'Painting and decorating trades': 'Sonstige',
  'Private households': 'Sonstige',
  'Pure transit': 'Sonstige',
  'Roofing trade': 'Sonstige',
  'Stonemason and stone sculptor': 'Sonstige',
};
