export enum Targets {
  Belgium = 'Belgium',
  Bulgaria = 'Bulgaria',
  Germany = 'Germany',
  Netherlands = 'Netherlands',
  Austria = 'Austria',
  Sweden = 'Sweden',
  CzechRepublic = 'Czech Republic',
  Portugal = 'Portugal',
  Finland = 'Finland',
  Slovenia = 'Slovenia',
  Lithuania = 'Lithuania',
  Switzerland = 'Switzerland',
  Hungary = 'Hungary',
  Malta = 'Malta',
  Slovakia = 'Slovakia',
  Poland = 'Poland',
  France = 'France',
  Denmark = 'Denmark',
}
